# Generated by Django 5.0.3 on 2024-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='failed_otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_failed_otp_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
