# Generated by Django 5.0.3 on 2024-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_failed_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_sms_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='sms_request_count',
            field=models.IntegerField(default=0),
        ),
    ]
