# Generated by Django 5.0.3 on 2024-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_ipaddress_blocked_until_ipaddress_last_sms_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp_activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
